# Generated by Django 4.2.9 on 2024-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="author status"),
        ),
    ]
