# Generated by Django 4.2.9 on 2024-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_is_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default="logo.webp", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="def.jpg", null=True, upload_to=""),
        ),
    ]
