# Generated by Django 4.2.9 on 2024-01-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_article_image_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.FileField(null=True, upload_to="pdfs/"),
        ),
    ]
