# Generated by Django 4.2.9 on 2024-01-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_article_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
