# Generated by Django 4.2.9 on 2024-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(default="logo.webp", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
