# Generated by Django 4.2.9 on 2024-01-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_article_image_alter_user_bio_alter_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["updated", "created"]},
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
